baseURL = 'https://sayoko123f.github.io/testgo/'
languageCode = 'zh-TW'
title = 'My New Hugo Site'
theme = 'devblog'
enableEmoji = true

[Params]
    author = 'Sayoko123f'
    github = 'https://github.com/Sayoko123f'